version: "3.8"
services:
  db:
    image: supabase/postgres:15.1.0.117
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  studio:
    image: supabase/studio:20240327-7a0ce43
    restart: always
    ports:
      - "54323:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: postgres

  kong:
    image: kong:2.8.1
    restart: always
    ports:
      - "54321:8000"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
    volumes:
      - ./kong.yml:/kong.yml:ro

  meta:
    image: supabase/postgres-meta:v0.75.0
    restart: always
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: postgres

volumes:
  db-data: 